### ISSUE TITLE
Understanding how the waveforms are generated in Rekordbox

### ISSUE THREAD

**Issue by david-res** [Deep-Symmetry/dysentery#55] opened 2024-08-11 18:58 UTC
I'd like to start off by saying this is a great assets to understanding how Rekordbox & the CDJs work together - I've found some very helpful information on here!

I'm building a "replica" CDJ 1000 / XDJ1000 using a Teensy 4.1 and I am analyzing the PCM audio before loading the track and generating a full waveform of the track into 150 lines per second of audio

I've been though tens of variations of analyzing code (using only maxPositive value, maxPositive-minNegative amplitude value etc) in linear view, as well as logarithmic view, but I am getting nowhere close to how the waveform is displayed on the CDJs.

Does anyone that has been reverse engineering the Rekordbox files have any clue what kind of algorithm they might be using to generate the waveform? I don't care as much for the multi colored waveforms, but rather, just the structure of the waveform.
I'd like to try and replicate it, but I am out of ideas and I've exhausted all my research leads

Thanks,

**Comment by brunchboy** [comment] 2024-08-11 23:50
Hello, David! To explore topics like this please use the [project discussion channel on Zulip](https://deep-symmetry.zulipchat.com/#narrow/stream/275855-dysentery-.26-crate-digger). Issues are for tracking work on actual defects or tasks that have been identified after discussion there.

That said, the way to generate waveforms like that involves using Fourier transforms so that you can work with the energy spectra in different frequency bands that are represented by the waveform data (in other words, moving to the frequency domain rather than the time domain). But we’ve never tried to reproduce what rekordbox does for us here, because we can simply have rekordbox do it for us.

**Closed by brunchboy** 2024-08-11 23:50 UTC
